name: Backend Deployment

on:
  push:
    branches: [ "main" ]        # auto deploy to staging on push
  workflow_dispatch:             # manual trigger for production

jobs:
  staging:
    name: Deploy to Staging
    runs-on: [self-hosted, staging_demo_1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy Backend on Staging
        run: |
          cd /home/ubuntu/backend
          sudo rm -rf *
          sudo cp -r $GITHUB_WORKSPACE/* .
          npm install
          sudo pm2 delete demo_backend || true
          sudo pm2 start server.js --name demo_backend
          sudo pm2 save

  production:
    name: Deploy to Production
    runs-on: [self-hosted, production_demo_2]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy Backend on Production
        run: |
          cd /home/ubuntu/backend
          sudo rm -rf *
          sudo cp -r $GITHUB_WORKSPACE/* .
          npm install
          sudo pm2 delete demo_backend || true
          sudo pm2 start server.js --name demo_backend
          sudo pm2 save
